### ISSUE TITLE
Daemonized chefs don't exit cleanly

### ISSUE THREAD

**Issue by ivanistheone** [learningequality/ricecooker#128]
* Python version: 3.6
* Operating System: Mac OS

### Description

daemonized chef runs don't stop cleanly

### What I Did

  - Started chef in daemonmode
  - ran it a few times
  - pressed CTRL + C to stop it

```
^CTraceback (most recent call last):
  File "./sample_program.py", line 507, in <module>
    chef.main()
  File "/Users/ivan/Projects/FLECode/ricecooker/ricecooker/chefs.py", line 291, in main
    self.daemon_mode(args, options)
  File "/Users/ivan/Projects/FLECode/ricecooker/ricecooker/chefs.py", line 268, in daemon_mode
    cws.join()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
^CException ignored in: <module 'threading' from '/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py'>
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1294, in _shutdown
    t.join()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1056, in join
    self._wait_for_tstate_lock()
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 1072, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

need to check why this traceback + make sure stops cleanly

**Comment by rtibbles** [comment]
No daemon mode any more.
