### ISSUE TITLE
Provide more meaningful message when user is not authorized to edit channel

### ISSUE THREAD

**Issue by jamalex** [learningequality/ricecooker#95]
* ricecooker version: 0.5.3
* Python version: 2.5.2
* Operating System: Ubuntu 16.0.4

### Description

Ran sushi chef, turned out I wasn't an editor on channel, but then only message shown was:

```
400 Client Error: Bad Request for url: https://contentworkshop.learningequality.org/api/internal/create_channel
Traceback (most recent call last):
  File "./chef.py", line 124, in <module>
    PhETSushiChef().main()
  File "/home/jamalex/fle/ricecooker/ricecooker/chefs.py", line 270, in main
    self.run(args, options)
  File "/home/jamalex/fle/ricecooker/ricecooker/chefs.py", line 260, in run
    uploadchannel_wrapper(self, args, options)
  File "/home/jamalex/fle/ricecooker/ricecooker/commands.py", line 33, in uploadchannel_wrapper
    uploadchannel(chef, **args_and_options)
  File "/home/jamalex/fle/ricecooker/ricecooker/commands.py", line 149, in uploadchannel
    config.PROGRESS_MANAGER.set_channel_created(*create_tree(tree))
  File "/home/jamalex/fle/ricecooker/ricecooker/commands.py", line 277, in create_tree
    channel_id, channel_link = tree.upload_tree()
  File "/home/jamalex/fle/ricecooker/ricecooker/managers/tree.py", line 152, in upload_tree
    root, channel_id = self.add_channel()
  File "/home/jamalex/fle/ricecooker/ricecooker/managers/tree.py", line 204, in add_channel
    response.raise_for_status()
  File "/home/jamalex/.virtualenvs/sushi-chef-phet/lib/python3.5/site-packages/requests/models.py", line 937, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://contentworkshop.learningequality.org/api/internal/create_channel
```

Only by checking the GCloud error dashboard could I see the cause:
![image](https://user-images.githubusercontent.com/618416/27817842-f60290cc-6047-11e7-897b-fe06ef721b60.png)

**Comment by ivanistheone** [comment]
+1 for fixing this :)

Today, one hour of running EngageNY lang=ar and then:

```

	Got file diff for 9131 out of 9131 files
Uploading files...

Uploading 0 new file(s) to Kolibri Studio...
Creating channel...

Creating tree on Kolibri Studio...
   Creating channel EngageNY (ar)
500 Server Error: User is not authorized to edit this channel for url: https://contentworkshop.learningequality.org/api/internal/create_channel
Traceback (most recent call last):
  File "./engageny_chef.py", line 844, in <module>
    chef.main()
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/chefs.py", line 296, in main
    self.run(args, options)
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/chefs.py", line 287, in run
    uploadchannel_wrapper(self, args, options)
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/commands.py", line 33, in uploadchannel_wrapper
    uploadchannel(chef, **args_and_options)
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/commands.py", line 164, in uploadchannel
    config.PROGRESS_MANAGER.set_channel_created(*create_tree(tree))
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/commands.py", line 292, in create_tree
    channel_id, channel_link = tree.upload_tree()
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/managers/tree.py", line 155, in upload_tree
    root, channel_id = self.add_channel()
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/ricecooker/managers/tree.py", line 218, in add_channel
    response.raise_for_status()
  File "/data/sushi-chef-engageny/venv/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: User is not authorized to edit this channel for url: https://contentworkshop.learningequality.org/api/internal/create_channel
```

**Comment by ivanistheone** [comment]
Possible solution -- error out early: `SushiChef`s `run` method should make a call to `/api/internal/check_user_is_editor` before calling the chef's `construct_channel` method
https://docs.google.com/spreadsheets/d/181hSEwJ7yVmMh7LEwaHENqQetYSsbSDwybHTO_0zZM0/edit#gid=0&range=A112

**Comment by benjaoming** [comment]
Got confused by this as well :+1: 

For @jamalex 's problem, here's a mockup solution for current Studio, but I think the issue should be filed there, since the response code is un-semantic and should have an error message.

```
diff --git a/contentcuration/contentcuration/views/internal.py b/contentcuration/contentcuration/views/internal.py
index e7e82c43..648a80c7 100644
--- a/contentcuration/contentcuration/views/internal.py
+++ b/contentcuration/contentcuration/views/internal.py
@@ -8,7 +8,6 @@ from past.builtins import basestring
 from django.core.exceptions import ObjectDoesNotExist
 from django.core.exceptions import PermissionDenied
-from django.core.exceptions import SuspiciousOperation
 from django.core.management import call_command
 from django.db import transaction
 from django.http import HttpResponseBadRequest
@@ -464,8 +463,8 @@ def create_channel(channel_data, user):
     # Otherwise, check if user is an editor
     if isNew or channel.editors.count() == 0:
         channel.editors.add(user)
-    elif user not in channel.editors.all():
-        raise SuspiciousOperation("User is not authorized to edit this channel")
+    elif not channel.editors.filter(pk=user.pk):
+        raise PermissionDenied("User is not authorized to edit this channel")
     channel.name = channel_data['name']
     channel.description = channel_data['description']
```

**Comment by ivanistheone** [comment]
This is causing also an issue as part of new cheffing onboarding. If a new ricecooker simply copy-pastes the sample code from the getting started tutorial https://github.com/learningequality/ricecooker/blob/master/examples/gettingstarted/sushichef.py they will get an error when they run the script.

`Error connecting to API: User is not authorized to edit this channel`


**Developer UX Idea**: the message could be more descriptive and suggest to the developer to check the value of source domain and channel source id (for getting started channel), or tell them to contact the channel authors/editors to ask for an invittion.
